services:
  postgres_db:
    image: postgres:latest
    container_name: broke_bank_pg
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: broke-bank
      POSTGRES_PASSWORD: 5up3r_s3cur3_p4ssw0rd
    ports:
      - "5432:5432"

  valkey:
    image: valkey/valkey
    container_name: broke_bank_valkey
    command: valkey-server
    ports:
      - "6379:6379"

volumes:
  postgres-data: null